USE sql_store;  
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SELECT *
FROM customers
WHERE customer_id = 1;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
SELECT *
FROM customers
WHERE customer_id = 1;

START TRANSACTION;
UPDATE customers
SET points = 2273
WHERE customer_id = 1;
COMMIT;